# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'approveDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_approveDialog(object):
    def setupUi(self, approveDialog):
        approveDialog.setObjectName("approveDialog")
        approveDialog.resize(200, 160)
        approveDialog.setStyleSheet("QDialog { background-color: #FFFFFF; }")
        self.exitPushButton = QtWidgets.QPushButton(approveDialog)
        self.exitPushButton.setGeometry(QtCore.QRect(50, 110, 100, 30))
        self.exitPushButton.setStyleSheet("QPushButton { color:blue; border: 1.0px solid blue; } QPushButton:hover { background-color: rgb(240,240,240); }")
        self.exitPushButton.setObjectName("exitPushButton")
        self.textLabel = QtWidgets.QLabel(approveDialog)
        self.textLabel.setGeometry(QtCore.QRect(20, 10, 160, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textLabel.setFont(font)
        self.textLabel.setStyleSheet("QLabel { color: red; }")
        self.textLabel.setObjectName("textLabel")

        self.retranslateUi(approveDialog)
        QtCore.QMetaObject.connectSlotsByName(approveDialog)

    def retranslateUi(self, approveDialog):
        _translate = QtCore.QCoreApplication.translate
        approveDialog.setWindowTitle(_translate("approveDialog", "Approval"))
        self.exitPushButton.setText(_translate("approveDialog", "EXIT"))
        self.textLabel.setText(_translate("approveDialog", "Thank you for\n"
"  your approval !\n"
"(≧∀≦) Respect !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    approveDialog = QtWidgets.QDialog()
    ui = Ui_approveDialog()
    ui.setupUi(approveDialog)
    approveDialog.show()
    sys.exit(app.exec_())
