# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nowayDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nowayDialog(object):
    def setupUi(self, nowayDialog):
        nowayDialog.setObjectName("nowayDialog")
        nowayDialog.resize(200, 160)
        nowayDialog.setStyleSheet("QDialog { background-color: #FFFFFF; }")
        self.nowayTextLabel = QtWidgets.QLabel(nowayDialog)
        self.nowayTextLabel.setGeometry(QtCore.QRect(80, 40, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nowayTextLabel.setFont(font)
        self.nowayTextLabel.setStyleSheet("")
        self.nowayTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nowayTextLabel.setObjectName("nowayTextLabel")
        self.xmarkGraphicsView = QtWidgets.QGraphicsView(nowayDialog)
        self.xmarkGraphicsView.setGeometry(QtCore.QRect(30, 40, 40, 40))
        self.xmarkGraphicsView.setStyleSheet("border: 0px;")
        self.xmarkGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.xmarkGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.xmarkGraphicsView.setObjectName("xmarkGraphicsView")
        self.okPushButton = QtWidgets.QPushButton(nowayDialog)
        self.okPushButton.setGeometry(QtCore.QRect(50, 110, 100, 30))
        self.okPushButton.setStyleSheet("QPushButton { border: 1.5px solid blue; } QPushButton:hover { background-color: rgb(240,240,240); }")
        self.okPushButton.setObjectName("okPushButton")

        self.retranslateUi(nowayDialog)
        QtCore.QMetaObject.connectSlotsByName(nowayDialog)

    def retranslateUi(self, nowayDialog):
        _translate = QtCore.QCoreApplication.translate
        nowayDialog.setWindowTitle(_translate("nowayDialog", "Warning"))
        self.nowayTextLabel.setText(_translate("nowayDialog", "No Way !"))
        self.okPushButton.setText(_translate("nowayDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nowayDialog = QtWidgets.QDialog()
    ui = Ui_nowayDialog()
    ui.setupUi(nowayDialog)
    nowayDialog.show()
    sys.exit(app.exec_())
